### ISSUE TITLE
Missing errors for bad/no alignment

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/flxlibs#100]
In integration testing yesterday (14 Nov) we stumbled repeatedly on errors in the FELIX, particularly lacking alignment. It would be helpful if the card controller or something could recognize and report these errors (at configuration time and/or runtime).

**Comment by ShyamB97** [comment]
So as a start I'll start adding error messages for when then link alignment fails, and then also do a check for the link alignment during the configuration step.

**Comment by wesketchum** [comment]
Fixed.
