### ISSUE TITLE
Should data errors be fatal to a run?

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/flxlibs#104]
e.g. "Unexpected chunk size", which usually results in corrupted data which can cause failures later on in the DAQ. I think that errors of this kind should stop at least the relevant readout process so that the issue on the hardware can be addressed.

**Comment by roland-sipos** [comment]
Absolutely not. 
There might be transmission errors happening between the frontend and the card. In this case block errors might happen with corrupted user payloads (chunks) in the datastream. flxlibs and the backend (readoutlibs) is resilient about this and proper error handling is implemented: block error counters, CRC check, timestamp checks.

Keep in mind, that links are recoverable. So the opmon metrics about ongoing errors are crucial to understand what goes wrong with the electronics. So I would say, it's actually essential to NOT teardown the process.

Also... in case a single FEMB goes haywire, we don't want to ers::fatal an overall APA equivalent of readout process. 

So all in all: Absolutely no fatal should be issued. Corrupted data is monitored, and does not end up downstream anyway.
