### ISSUE TITLE
CardWrapper::stop process random elinks

### ISSUE THREAD

**Issue by MBoretto** [DUNE-DAQ/flxlibs#17]
https://github.com/DUNE-DAQ/flxlibs/blob/eab1018a1c3924c5a78eeebfd9b74ad12534d7d9/src/CardWrapper.cpp#L120

I noticed that the DMA thread start processing un-existing elinks when the CardWrapper::stop is invoked. 
To avoid that the code have to be changed from:
```
    stop_DMA();
    set_running(false);
    while (!m_dma_processor.get_readiness()) {
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    init_DMA();
```

to 

```
    set_running(false);
    while (!m_dma_processor.get_readiness()) {
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }
    stop_DMA();
    init_DMA();
```

**Comment by roland-sipos** [comment]
Fixed in 3cb2275

Thanks Marco
