### ISSUE TITLE
FlxCardReader's ELink configuration revamp

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/flxlibs#27]
Better FELIX card ELink/DMA configuration

- instead of num_links, move to a link_mask list, which elink processors to set up 
- elink_mask config should have (link_id, dma_id) pairs as DMA descriptor is configurable per link 
- update local configuration generator in flxlibs, moving to the changes above, and to generate FlxCardReader modules for reading FW TP links |

**Comment by ShyamB97** [comment]
- PR for FelixCardReader changes made
  - branch for app_confgen,py changes made
