### ISSUE TITLE
Config generator for FelixCardController

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/flxlibs#28]
Introduce config generator for FelixCardController to provide regmap settings for enabling/disabling links, and calling GTH reset after CardReaders are configured

**Comment by dingp** [comment]
I saw the issue has been assigned to `SW Cooridnation` working group. Is this by mistake or intended?

**Comment by roland-sipos** [comment]
Thanks for noticing Pengfei, indeed it was a mistake.
