### ISSUE TITLE
Update integration test documentation

### ISSUE THREAD

**Issue by ShyamB97** [DUNE-DAQ/flxlibs#36]
Update [integration test documentation](https://github.com/DUNE-DAQ/flxlibs/wiki/Integration-tests) to include:
 - spreadsheet of tests conducted + status for different FW/SW versions
 - description of basic setup and how to run the tests
 - bash scripts to run the various tests
 
Initial list of integration tests:
- Program card
    - Program FPGA
    - Program FLASH

 - Standalone tools
     - Test card communication & control - reset/init/info
     - Test ADC data flow with emulator (10 link) - FixedHits_A
     - Test ADC data flow with optical input/ZCU102 (10 link) - FixedHits_A
     - Test TPG with wibulator (SLR 1, 1 channel ?) - FixedHits_A
     - Test TPG with wibulator (SLR 2, 1 channel ?) - FixedHits_A
     - Test TPG with wibulator (SLR 1&2, 1 channel per SLR ?) - FixedHits_A
     - Test TPG with FLX emulator (SLR 1&2, 1 channel per SLR ?) - FixedHits_A
     - Test TPG with optical input/ZCU102 (SLR 1&2, 1 channel per SLR ?) - FixedHits_A
     - Test TPG with ZCU102 (SLR 1&2, multiple channels) - FixedHits_A (buffer at 50% capacity)

 - Dunedaq integration tests
    - Test ADC recording with emulator (10 link) - FixedHits_A
    - Test ADC recording with optical input/ZCU102 (10 link) - FixedHits_A
    - Test TPG recording with emulator (10 link) - FixedHits_A
    - Test TPG recording with optical input (10 link) - FixedHits_A

**Comment by ShyamB97** [comment]
Documentation is updated to include instrucutions (and resources) to run the standalone tool tests.
@kkothekar can you go through these instructions?

**Comment by kkothekar** [comment]
@ShyamB97 I have gone through the instructions, and done all the test except the last one. You can check the status with my comments here: [https://docs.google.com/spreadsheets/d/1wXz7qx9HzWGdVpDBZSh985ecvFOZMB51oAWpZzaUU-k/edit?usp=sharing](url)

**Comment by ShyamB97** [comment]
@kkothekar Thanks. Can you add this link to the spreadsheet at the top of the wiki page?

**Comment by kkothekar** [comment]
@ShyamB97 done.

**Comment by kkothekar** [comment]
@ShyamB97 `set_gbt.sh` needs a slight change, change line 28 and 33 to:
`watch -c "hfButler.py flx-0-p2-hf link -i 4 watch -RB | grep -v WARNING"`

tp-link processes were not visible, adding specific link no. to the watch command will enable to see the data flowing on tp-link.

**Comment by kkothekar** [comment]
@ShyamB97 Also there are some issues I have written in the comments section of the test document, could you give your feedback on them.
