### ISSUE TITLE
Emulator config doesn't load expected EMU data

### ISSUE THREAD

**Issue by ngiangia** [DUNE-DAQ/flxlibs#5]
Apparently emulator can't be configured only by changing FLX registers

**Comment by ngiangia** [comment]
It looks like there is no need to touch the code. The only requirement is to add few (30k) lines to the  config files

**Comment by roland-sipos** [comment]
New tool from @ngiangia  in 0ea33e7857647715d139368cf574c44841b5a543 fixes this. Instructions added to the wiki.
