### ISSUE TITLE
DMA flush

### ISSUE THREAD

**Issue by ShyamB97** [DUNE-DAQ/flxlibs#51]
(Observed only on np04-srv-030)
If the contents of DMA not flushed, then re-configuring the card (`flx-info`, `flx-config` etc.) will cause the system to crash and manual reboot is required.

One way to overcome this is to run `fdaq` before re-configuring the FELIX, to allow the DMA to be flushed i.e. after a readout application crash:
```
fdaq -d 0 -t 5
fdaq -d 1 -t 5

# now reconfigure card
```

**Comment by wesketchum** [comment]
@roland-sipos @ShyamB97 @glehmannmiotto is this still an issue/something that we need to try to understand? We've just plugged in `np04-srv-030` to APA2 ...

**Comment by roland-sipos** [comment]
I'm very puzzled by this... 
The `dma_fifo_flush` was marked as obsolete in FlxCard:
https://gitlab.cern.ch/atlas-tdaq-felix/flxcard/-/blob/master/src/flx-dma-test.cpp#L112

On configuring the CardWrapper, the initDMA is called:
https://github.com/DUNE-DAQ/flxlibs/blob/7a096e7a77c28020b97fe1830d18a1fc7214345d/src/CardWrapper.cpp#L222

This follows the right sequency of card -> driver -> software interactions to reset the DMA.

Was this system crash observed with firmware TPG active? I'd say that I don't see any issue with the conventional raw readout side of the FELIX. This must be an issue somewhere in FELIX CR / TPG block / software interactions.

Without a reproducible test-scenario, I'm hesitant to change anything on the current reset implementation. I'd propose to investigate the issue first with the FELIX developers, including a reproducible test with explicit versions for:
- the firmware
- driver
- software used (flxcard and friends)

**Comment by ShyamB97** [comment]
So this was tested with firmware TPs and the v2.0.0 version of FELIX firmware (so a few months old at this point) so it's possible that the many updates to the firmware might have resolved the issue. But since the VD coldbox run tests haven't been done on np04-srv-030. I also can confirm the issue was not observed for ADC readout because the combination of software/fw/drivers was used during the VD coldbox run for ADC readout and swtp runs.

**Comment by roland-sipos** [comment]
Thanks @ShyamB97 . Closing issue until we see similar system-wide crashes again.
