### ISSUE TITLE
Include TPG pattern test in integration tests

### ISSUE THREAD

**Issue by jimbrooke** [DUNE-DAQ/flxlibs#69]
Integration tests currently do not verify data corresponds to what is expected; they just check that the dataflow runs without errors.  We should add a check that the data is "correct", particularly important for TPG data.

**Comment by roland-sipos** [comment]
@ShyamB97 is this done?

**Comment by ShyamB97** [comment]
Note sure, @kkothekar was planning to look at this a while ago, is there any progress?

**Comment by roland-sipos** [comment]
Won't fix.
