### ISSUE TITLE
instructions/procedures for multiple numa nodes needs updating

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/flxlibs#98]
@ShyamB97 @roland-sipos , others...

After the reinstall of np04-srv-028, the felix driver came back up just fine, but we were unable to readout the second card, getting
```
FELIX Card Internal Error: Not enough CMEM memory allocated or the application demands too much CMEM memory. Fix the CMEM memory reservation in the driver or change the module's configuration
```
errors during configuration of the readout app.

@ShyamB97 and I tracked this down to the driver running with `numa_zones: 1`. We were able to fix it by specifying the cmem driver module parameter in `drivers_flx_local`:

```
export CMEM_PARAMS="gfpbpa_size=8192 gfpbpa_quantum=4 numa_zones=2"
```

We should add this to documentation at minimum. I'd recommend that if we want a default to be 1, then we should still explicitly add it in the cmem_params as 1 so it's easy to see that's its default. Maybe there's a better way to handle this automatically?

**Comment by roland-sipos** [comment]
This is incorrect.... I'm not sure numa_zones=2 from CMEM_PARAMS is picked up. I needed to rebuild the driver with a similar static variable updated in cmem_rcc.c
We can definitely test it.

**Comment by wesketchum** [comment]
It had been picked up in our testing before. I think that it takes this as an argument into the cmem driver, so that one doesn't need to recompile changing the static variable.

**Comment by wesketchum** [comment]
Closing for now.
